### ISSUE TITLE
Doorkeeper::Config.option -- what is the intended purpose ? for it to be private or public

### ISSUE THREAD

**Issue by arjun9** [doorkeeper-gem/doorkeeper#1017]
Removed  **extended**
   def extended(base)
      base.send(:private, :option)
   end
from **Doorkeeper::Config**, and none of the tests fail. 
What was the intended purpose for *option* ?

**Comment by nbulaj** [comment]
Hi @arjun9 . What is the issue? `option` is used to define Doorkeeper options, you can see them [there](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L236-L249). `extended` hook is just a legacy, that still in master because of 6 years ago [refactoring](https://github.com/doorkeeper-gem/doorkeeper/commit/f9bab6fef4960e137f319435b4fe5ec42f6bd577).

**Comment by arjun9** [comment]
Hi @nbulaj ,
```
def extended(base)
    base.send(:private, :option)
end
```
doesn't actually extend option method as a **private** class method in class Config.
I commented out this code and ran Doorkeeper tests and there were no test cases failing - stating that this snippet of code is not actually being used anywhere. 

I extended - option method-  as a **private** method in class Config which led to tests failing.

I found this snippet a little misleading - hence wanted to clarify its purpose.

**Comment by nbulaj** [comment]
It's because somebody forgot about `self.extended`, not just `extended`. I think it was done during the [refactoring 6 years ago](https://github.com/doorkeeper-gem/doorkeeper/commit/f9bab6fef4960e137f319435b4fe5ec42f6bd577). I will take a look at it closer soon, thanks.
