### ISSUE TITLE
Text type for scopes field

### ISSUE THREAD

**Issue by rishabhsairawat** [doorkeeper-gem/doorkeeper#1094]
Currently, Doorkeeper uses string type for `scopes` but If the number of scopes is very large then character limit for string will exceed. So Isn't it better to use text type for `scopes`?
If yes, then would you like a PR for that?

**Comment by nbulaj** [comment]
Yep, but there are no problems with string type, because for example in PostgreSQL without `limit` option this column would be a `character varying`, that is recommended (the same as `text`) for long strings, see https://www.postgresql.org/docs/10/static/datatype-character.html MySQL, as far as I remember, also allows variable length for varchar strings ( need to see https://dev.mysql.com/doc/refman/5.7/en/char.html ). There are could be some questions aroubd performance of this types if it matters. Also, anyone can change the main Doorkeeper migration to use `text` column. But we are an opionated OAuth framework, so maybe it must be the better choise by default..

**Comment by nbulaj** [comment]
Hi @rishabhsairawat . I've decided not to change column type for `scopes` as it doesn't make sense: PostgreSQL, SQLite, MySQL and MSSQL doesn't force a characters limit for `varchar` (if limit is not defined).
