### ISSUE TITLE
Post /oauth/token returning 500

### ISSUE THREAD

**Issue by hszeto** [doorkeeper-gem/doorkeeper#1179]
**Ruby version**: 2.5.1
**doorkeeper version**: 5.0.1

I'm getting 500 for POST to /oauth/token without the client_id. Is this an expected behavior?

How I obtain the auth code:
```
client = OAuth2::Client.new(client_id, client_secret, :site => site)
client.auth_code.authorize_url(:redirect_uri => redirect_uri)
visit=> http://localhost:3000/oauth/authorize?response_type=code&client_id=...&redirect_uri=...
```
Post token:
```
curl -X POST \
  http://localhost:3000/oauth/token \
  -H 'Content-Type: application/json' \
  -d '{
     "grant_type":"authorization_code",
     "code":"34c34012......40e28cb",
     "client_secret": "4a48e7653b......c0d4f6e3c62f54a",
     "redirect_uri": "http://localhost:3000/callback"
  }'
```

**Comment by hszeto** [comment]
I also observe that, POST /oauth/token without the client secret will return the access token.

```
curl -X POST \
  http://localhost:3000/oauth/token \
  -H 'Content-Type: application/json' \
  -d '{
     "grant_type":"authorization_code",
     "code":"34c34012......40e28cb",
     "client_id":"2c4fd1ccc118c27......156c82a696e7",
     "redirect_uri": "http://localhost:3000/callback"
  }'
```

I  thought the client secret is Required when exchange the code for the access token.

**Comment by ZilvinasKucinskas** [comment]
@hszeto I can verify this is an issue and it should return something like `invalid_client` instead of 500 error. I want to volunteer and fix this issue and open a PR to Doorkeeper.

In regards to the second comment, `client_secret` is not required when using `Authorization Code Grant Flow` as described in [RFC6749](https://tools.ietf.org/html/rfc6749#section-4.1.1).

* If your application is confidential, `client_secret` is required.
* If your application is public, `client_secret` is not required. Public applications are insecure by default.

[More information about client types](https://tools.ietf.org/html/rfc6749#section-2.1)

Check your application - probably `application.confidential` is set to `false`.
