### ISSUE TITLE
Password grant flow for mobile app + refresh tokens issues?

### ISSUE THREAD

**Issue by zenzei** [doorkeeper-gem/doorkeeper#1292]
Hello!
I have Rails 5.2.2 web app and i'm adding an API for mobile clients that will be authenticated through doorkeeper (v5.1.0). Users/signup is already managed by devise (v4.5.0).

People will login once on the mobile app with their credentials, so i was planning to use the password flow grant and then using refresh tokens so they don't have to enter their credentials again, unless they logged out.

I already set up the authorization/authentication with both doorkeeper and devise (refresh tokens enabled and sign up through devise / sign in through doorkeeper ).  In doorkeeper config i have this for authentication with devise.

```
  resource_owner_from_credentials do |_routes|
    user = User.find_for_database_authentication(email: params[:username])
    if user && user.valid_password?(params[:password])
      request.env['warden'].set_user(user, scope: :user, store: false)
      user 
    end
  end
```

Doorkeeper is providing both access and refresh tokens ok after login, for example.
```
curl -F grant_type=password \
-F username=user@example.com \
-F password=doorkeeper \
-X POST http://localhost:3000/oauth/token
```

I do get
```
{
    "access_token": "i4uUIuSPS3yexG6MnWx77Hu08hAc6-RctR4RyGNY2Vs",
    "token_type": "Bearer",
    "expires_in": 7200,
    "refresh_token": "Em1Czlf8WRn1g23pRADUNC4DakcGKwCsy4ubuz1HQzY",
    "created_at": 1564345586,
    }
}
```

So was trying to see how the refresh token workflow should work and found an example here https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples, so i check the call with

```
curl -F grant_type=refresh_token
-F refresh_token=Em1Czlf8WRn1g23pRADUNC4DakcGKwCsy4ubuz1HQzY
-X POST http://localhost:3000/oauth/token
```

But as i see this call generates not only a new access token, but also a new refresh token. 

```
{
    "access_token": "R6B_tOiZ0loYfmNwP5ArNpX3JnT8uSXWjgpbpzh-T4g",
    "token_type": "Bearer",
    "expires_in": 7200,
    "refresh_token": "QgZe8Ns-zqWVpOBb1GCXWXC3ngi1Ltpv1KB1oFOa2YA",
    "created_at": 1564346058,
    }
}
```

The thing is testing the new and old refresh tokens, both of them are valid, as i can generate new access tokens with both them.
So is this an error? Shouldn't the first refresh token be somehow invalidated, or instead this call return the same refresh token as before? 

Another issue i found is with revoke token as i think is something i should call if people logout from the app (or should i use another method?). If i do the call to revoke
```
curl -F token=i4uUIuSPS3yexG6MnWx77Hu08hAc6-RctR4RyGNY2Vs \
-X POST http://localhost:3000/oauth/revoke
```

I do see that the column revoked_at is correctly updated for that token on the DB. But if i try to authorize another call with the revoked access_token, it doesn't trigger an error, it just authorize it. 

```
curl -X GET http://localhost:3000/api/ping?access_token=i4uUIuSPS3yexG6MnWx77Hu08hAc6-RctR4RyGNY2Vs
```

Return code 200 (This is a simple call i have that returns nothing but the status code).

The authorization workflow is working because if i use an invalid access_token like this
```
curl -X GET http://localhost:3000/api/ping?access_token=i4uUIuSPS3
```
I do get a code 401 Unauthorized.

So are these two errors, or maybe this is not the right workflow to use for password grant with refresh tokens? 

Thanks in advance!

PS: Somehow related, is there a recommended way to force an invalidation of all access/refresh tokens realated to a user if for example that user change his/her password?

**Comment by nbulaj** [comment]
Hi @zenzei .

1. First of all about refresh tokens

> The thing is testing the new and old refresh tokens, both of them are valid,
> So is this an error? Shouldn't the first refresh token be somehow invalidated, or instead this call return the same refresh token as before?

As far as I remember it doesn't proposed by the RFC, but need to check. But definitely you can call token revocation endpoint that is actually created for such purposes (see https://tools.ietf.org/html/rfc7009#section-2 ). Also check [1.5.  Refresh Token](https://tools.ietf.org/html/rfc6749#section-1.5) section of RFC6749 that says nothing about refresh token invalidation. Moreover, if you are using JWT tokens, it's can't be done by design (but only if you create a "blacklist" of refresh tokens and integrate it with your OAauth2 provider).

But from the other side, we have [6.  Refreshing an Access Token](https://tools.ietf.org/html/rfc6749#section-1.5) section that says:

> The authorization server MAY issue a new refresh token, in which case
> the client MUST discard the old refresh token and replace it with the
> new refresh token.  The authorization server MAY revoke the old
> refresh token after issuing a new refresh token to the client.  If a
> new refresh token is issued, the refresh token scope MUST be
> identical to that of the refresh token included by the client in the
> request.

Se need to double-check it when I have time.

2. About revoked token used

>  But if i try to authorize another call with the revoked access_token, it doesn't trigger an error

Actually it couldn't be because of:

* `doorkeeper_authorize!` check the token by calling `valid_doorkeeper_token?`
* `valid_doorkeeper_token?` check if token from the request is accessible with the scopes configured - `acceptable?(@_doorkeeper_scopes)` ( see https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/rails/helpers.rb#L17 )
* `acceptable?` checks if Access Token `accessible?` and has such scopes, see https://github.com/doorkeeper-gem/doorkeeper/blob/00b4aa1613b6a1203bf9460785f2d3989b515c09/lib/doorkeeper/models/access_token_mixin.rb#L275
* anf the last one - `accessible?` - check Access Token to not be a revoked or expired (see https://github.com/doorkeeper-gem/doorkeeper/blob/72425150a95c4c5874ac2926b0ede90e705bd736/lib/doorkeeper/models/concerns/accessible.rb#L11)

So I recommend you to double-check if you are using token you supposed to.

**Comment by nbulaj** [comment]
I check our `refresh token` strategy implementation and seems like we actually revoke the refresh token :thinking: 

Check this:

https://github.com/doorkeeper-gem/doorkeeper/blob/94dfa31df04cfddde4fb18eb2f4a6f04ed33d9a2/lib/doorkeeper/oauth/refresh_token_request.rb#L37

And this: 

https://github.com/doorkeeper-gem/doorkeeper/blob/4dc432c74a424c85e141b131939faafa98a916fc/lib/doorkeeper/oauth/token.rb#L20

And the tests for it:

https://github.com/doorkeeper-gem/doorkeeper/blob/78347f8a2f6a848369ce398491ae06c7b4279446/spec/requests/flows/refresh_token_spec.rb#L74

So I once again recommend to double check which token values, of what type, on what endpoint and so on do you use. Or try to add some spec for this gem that shows the wrong behavior (as a PR for example or gist). Thanks!

**Comment by zenzei** [comment]
Hello @nbulaj. My apologies, it seems it was my error, i discover what was happening after checking the code you point out.

(1) refresh tokens revoked. 

The refresh tokens where not revoked because i was not using the new access tokens. I thought  they were instantanely revoked, but discover they don't when i saw the "refresh_token_revoked_on_use" check (https://github.com/doorkeeper-gem/doorkeeper/pull/769). 

(2) revoked access tokens being "valid".
The problem here seems to be more related to devise. I was doing this check on my controller
_before_action :doorkeeper_authorize!  , unless: :user_signed_in?_

It seems there is some kind of session persisted when i sign in my API through devise, and the doorkeper authorize was not triggered.  After removing the "unless" condition it works. 

I'm still not sure though why the call was failing only when i was using a wrong token (that's why i thought the doorkeeper authroized was being triggered), and not failing when using a token existant on the DB, but i don't think now it was a doorkeeper problem.


So again my apologies for this, hope it helps as reference if someone does the same mistakes as i did.

By the way thank you so much for the gem!

**Comment by zenzei** [comment]
Sorry @nbulaj, i forgot the related question, is there a recommended way to force an invalidation of all access/refresh tokens related to a user in special ocassions (like users changing their passwords)?
