### ISSUE TITLE
Attempting to revoke an invalid token responds with an error

### ISSUE THREAD

**Issue by JoshNorthrup** [doorkeeper-gem/doorkeeper#1362]
### Steps to reproduce
When making a properly formed revocation request (`POST /oauth/revoke`) with an invalid token, a 403 is returned.  This seems to disagree with https://tools.ietf.org/html/rfc7009#section-2.2 which states 
```
The authorization server responds with HTTP status code 200 if the
token has been revoked successfully or if the client submitted an
invalid token.
```

### Expected behavior
Given a properly formed request with an invalid token, `TokensController#revoke` should respond with 200

**Comment by JoshNorthrup** [comment]
@nbulaj Thoughts on this? I can put together a PR

**Comment by nbulaj** [comment]
Hi @JoshNorthrup . I thought we have a proper implementation. Don't we have a specs for it in tests? :thinking: 

If not - would be great to see a PR! Thanks!
P.S. Sorry, boo busy to review everything

**Comment by nbulaj** [comment]
Actually I checked this https://github.com/doorkeeper-gem/doorkeeper/blob/b21370d7788724e52ef0df025083376c41bc74c9/app/controllers/doorkeeper/tokens_controller.rb#L13-L28 and and seems like it's a real issue, yep.

But we need to notice all the clients that will update Doorkeeper that we have such change because it's a breaking change. So after we'll merge the PR we must also update the docs (upgrade guides)

**Comment by nbulaj** [comment]
Hm , also reads this please: https://github.com/doorkeeper-gem/doorkeeper/pull/1252

**Comment by nbulaj** [comment]
Hm, or actually current authorization must be changed to:

* check whether client authorized
  * if yes - then do all the stuff and render 200
  * if not - do as we do now (respond with error)

**Comment by nbulaj** [comment]
Re-reviewed RFC and create a PR to fix the issue @JoshNorthrup , you could check #1370

**Comment by nbulaj** [comment]
Fixed, thanks @JoshNorthrup
