### ISSUE TITLE
Adding default_scopes invalidates all existing token

### ISSUE THREAD

**Issue by ch000** [doorkeeper-gem/doorkeeper#1399]
### Steps to reproduce
Add doorkeeper to application.
Add `before_action :doorkeeper_authorize!` to some controller.
Create access token.

Add `default_scopes  :public` to doorkeeper config and restart server.

Use previously created token to access controller action.

### Expected behavior
Token should be valid and action should be reached.

### Actual behavior
Requests halts with a 403 forbidden response.

I think this causes this behaviour
https://github.com/doorkeeper-gem/doorkeeper/blob/4375bd850b8052c651e45b73ea387b3d632361de/lib/doorkeeper/rails/helpers.rb#L6-L7

When we don't require any scopes for an action, we still check if the token includes the new  default_scopes.

Also in the documentation it says
> If the access token does not contain any of the scopes passed, then you'll get a 401 unauthorized response.
https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes#using-in-your-api

But somehow i get an 403 forbidden response. This makes it additionally hard to integrate scopes. Previously clients only needed to handle 401 responses and now they get a 403 response, even though it is a valid request and scopes aren't even needed for this action.
 
### System configuration

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  orm :active_record

  resource_owner_authenticator do
    current_user || warden.authenticate!(scope: :user)
  end

  resource_owner_from_credentials do |_routes|
    u = User.find_for_database_authentication(email: params[:email])
    u if u&.valid_password?(params[:password])
  end

  admin_authenticator do
    if current_user&.admin?
      current_user
    else
      respond_to do |format|
        format.html { render file: Rails.root.join('public', '404'), layout: false, status: :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end
  end

  use_refresh_token
  default_scopes  :public
  grant_flows %w[password]
end

```

doorkeeper version 4.2.6

**Comment by nbulaj** [comment]
Hi

> Adding default_scopes invalidates all existing token

This is actually an expected behavior. You already found that if you didn't set scopes required for the action in `doorkeeper_authorize` Doorkeeper will use default one which was changed.

If you do such breaking changes - you need to update your access tokens to include this scope yourself. 

> https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes#using-in-your-api

About this - I can't say you anything just because docs in the wiki could be outdated. And I honestly don't remember which status Doorkeepper uses. The source of truth is the OAuth RFC, and if it requires to return 401 or 403 - we must implement it like this. Of RFC doesn't specify this - we do it on our own.

**Comment by nbulaj** [comment]
Doorkeeper renders response status this way (code doesn't changed since 2014 if you'll do a git blame):

https://github.com/doorkeeper-gem/doorkeeper/blob/8fec40d5b873dc62e8bc29b8ebfe71a003b09dab/lib/doorkeeper/rails/helpers.rb#L52-L58

Since your scopes are invalid - it uses `ForbiddenTokenResponse` error. which is also didn't change from 2014:

https://github.com/doorkeeper-gem/doorkeeper/blob/78347f8a2f6a848369ce398491ae06c7b4279446/lib/doorkeeper/oauth/forbidden_token_response.rb#L15-L17

Maybe wiki page is _super_ outdated, I don't know

**Comment by nbulaj** [comment]
Hi @ch000 . Does your issue still actual ? Do you need more help? Or we can close it?

**Comment by ch000** [comment]
Ah yes, sorry! I manually added the new scopes to all existing token and everything worked fine. Thanks for your help and updating the wiki!
