### ISSUE TITLE
 undefined method `form_post_response?'

### ISSUE THREAD

**Issue by Maxeeezy** [doorkeeper-gem/doorkeeper#1444]
### Steps to reproduce
Copy authorizations controller code in application.
Run authorization -> if api_only == false the error will appear

### Expected behavior
should return a true/false

### Actual behavior
throws undefined method `form_post_response?'

Please check the controller code where you can find the method
https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb,
maybe a recent update with that missing method is the problem?

**Comment by nbulaj** [comment]
Hi @Maxeeezy . I think you're using stable version of the gem, but here - https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb - you see a `current` (master) version that is not released yet. That's why you see such error. You need to open a proper relese for the gem on GitHub with version of the gem you're using and copy the code from it

**Comment by Maxeeezy** [comment]
Thank you!
