### ISSUE TITLE
CanCan and Doorkeeper

### ISSUE THREAD

**Issue by glaucocustodio** [doorkeeper-gem/doorkeeper#252]
Hi guys, I have implemented doorkeeper in my project and created custom controllers and routes in order I can use layout from my application, however if I call any CanCan method inside custom controllers I get exception, is there no way to get it working? I cant let any user create oauth applications, I need to restrict through roles

See the gist: https://gist.github.com/glaucocustodio/5929646

Thank you.

**Comment by nbulaj** [comment]
@sagar-ranglani check the @hammady comment above, It's actually not Doorkeeper issue, but some misconfiguration between the gems/

**Comment by sagar-ranglani** [comment]
As stated by @hammady, that will fix the doorkeeper auth but the `current_user` for devise auth will be lost!
I need to have both in our application.

**Comment by sagar-ranglani** [comment]
The thing that worked for me was adding the following to the `application_controller.rb`

```
  alias devise_current_user current_user

  def current_user
    if devise_current_user
      devise_current_user
    else
      User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
    end
  end
```

**Comment by sagar-ranglani** [comment]
And that's not working either when I try to restart the server! :-(

**Comment by nbulaj** [comment]
Sorry, I don't work with CanCan / CanCanCan, so I can help with integration here. Maybe somebody from the community, you can try to ask on StackOverflow

**Comment by sagar-ranglani** [comment]
What finally worked for me was adding the following to the `application_controller.rb`

```
class ApplicationController < ActionController::Base
  def devise_current_user
    @devise_current_user ||= warden.authenticate(scope: :user)
  end

  def current_user
    if devise_current_user
      devise_current_user
    elsif doorkeeper_token
      User.find(doorkeeper_token.resource_owner_id)
    end
  end
end
```

**Comment by iamdriz** [comment]
Came across this as wanted to support CanCanCan for Doorkeeper but also support `client_credentials` flow. The solution I I came up with was Instead of messing with the `current_user` method we leave that as-is, and then introduce a new method for the resource owner (as recommended by the Doorkeeper docs) if someone has authenticated via a doorkeeper token instead of a session:

```
helper_method :current_resource_owner
def current_resource_owner
  @current_resource_owner ||= begin
    if doorkeeper_token&.resource_owner_id
      User.find(doorkeeper_token.resource_owner_id)
    end
  end
end
```

If the token doesn't have a `resource_owner_id` then it means it's a client credentials flow so the value will be `nil`. And so will `current_user` as there's no session.

The trick is to override the `current_ability` and pass both the `current_user` and `current_resource_owner` for the user parameter like so:

```
def current_ability
  @current_ability ||= Ability.new(current_user || current_resource_owner, doorkeeper_token)
end
```

You'll notice we also pass the `doorkeeper_token` so that we can have permissions at a client application level too. So in our Ability class we define abilities for either the user or the application:

```
class Ability
  include CanCan::Ability
  
   def initialize(user_or_resource_owner, doorkeeper_token = nil)
     if user_or_resource_owner
       define_user_abilities(user_or_resource_owner)
    elsif doorkeeper_token
      define_client_abilities(doorkeeper_token.application)
     end
   end
end
```

Hopefully this helps others who want a similar setup with Doorkeeper, Devise, and CanCanCan.
