### ISSUE TITLE
Manually authorize a user on a client app

### ISSUE THREAD

**Issue by barmstrong** [doorkeeper-gem/doorkeeper#284]
We have a spot where we'd like to manually authorize a user for an application, given it's client_id.  And return the relevant access_token/refresh_token to them.

After some trial and error we came up with this:

``` ruby
app = Doorkeeper::Application.where(uid: params[:client_id]).first
access_token = Doorkeeper::AccessToken.create!({
  :application_id     => app.id,
  :resource_owner_id  => @user.id,
  :scopes             => 'all',
  :expires_in         => Doorkeeper.configuration.access_token_expires_in,
  :use_refresh_token  => Doorkeeper.configuration.refresh_token_enabled?
})
@token_response = Doorkeeper::OAuth::TokenResponse.new(access_token)
puts @token_response.body
```

I'm posting this partially for anyone else who might want to know.  And also to double check if we are missing anything.  Thanks!

**Comment by woto** [comment]
https://github.com/doorkeeper-gem/doorkeeper/issues/846

**Comment by Catsuko** [comment]
>I'm posting this partially for anyone else who might want to know. And also to double check if we are missing anything. Thanks!

I think creating a token like this is not a good approach because it diverges from how Doorkeeper creates tokens and opens you up to all kinds of inconsistencies now or in the future.

For example:

If you decide to use the [custom access token configuration](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-Token-Expiration), this won't be applied to your manually created token since internally [determining expiration](https://github.com/doorkeeper-gem/doorkeeper/blob/v4.4.3/lib/doorkeeper/oauth/authorization/token.rb#L8-L14) is a bit more involved then just checking a config value.

Even if you copy the logic so the creation is the same, if you ever update the gem then you will need to ensure that your custom custom stays the same 🥲
