### ISSUE TITLE
Expire Refresh Tokens?

### ISSUE THREAD

**Issue by fabrik42** [doorkeeper-gem/doorkeeper#360]
Are there any plans to support a max TTL for refresh tokens?

As far as I understand it, a refresh token never expires.

I can't find something in the OAuth2 spec, that requires the server to set a TTL for a refresh token, but I would consider it good practice to never hand out tokens that are valid forever.

Maybe it would be a better idea to make the refresh token a long-living token by default (e.g. 30 days).

**Comment by GeminPatel** [comment]
@tute I am not able to find this spec. Max I could find was in https://tools.ietf.org/html/rfc6749#section-6

This line: "Because refresh tokens are typically long-lasting credentials used to
   request additional access tokens,......"

**Comment by parhs** [comment]
For SPA applications though this might be usefull 
https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-05#section-8

**Comment by gardner** [comment]
That seems to indicate that Doorkeeper does not conform to the spec? 

```
   o  MUST either set a maximum lifetime on refresh tokens OR expire if
      the refresh token has not been used within some amount of time
```

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps-05#section-8

**Comment by wjordan** [comment]
> That seems to indicate that Doorkeeper does not conform to the spec?

The linked document is not 'the spec', it's just a draft of recommendations for using OAuth 2.0 with browser-based apps. Also important to note that the quoted line is preceded by `If issuing refresh tokens to browser-based applications`, so an implementation that does not issue refresh tokens to browser-based applications (which is configurable in Doorkeeper) would still conform to that draft recommendation as well.

That said, I disagree with the argument that a refresh-token TTL _shouldn't_ be implemented just because it's not explicitly required by the spec (OAuth 2.0, RFC 6749), since the spec indeed comes quite close to recommending such an implementation in [Section 10.1](https://datatracker.ietf.org/doc/html/rfc6749#section-10.1):

>    The authorization server must consider the security implications of
   interacting with unauthenticated clients and take measures to limit
   the potential exposure of other credentials (e.g., refresh tokens)
   issued to such clients.

Also worth noting that the current [OAuth 2.1 draft](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-06#section-2.4) tweaks this language to recommend limiting the lifetime of refresh tokens a bit more explicitly:

>    The authorization server MUST consider the security implications of
   interacting with unauthenticated clients and take measures to limit
   the potential exposure of tokens issued to such clients, (e.g.,
   limiting the lifetime of refresh tokens).
