### ISSUE TITLE
Adding methods to `Doorkeeper::ApplicationController` (path helper related)

### ISSUE THREAD

**Issue by aymericbouzy** [doorkeeper-gem/doorkeeper#465]
oauth_authorized_application_path(application) fails systematically for me, with : 

No route matches {:action=>"destroy", :controller=>"doorkeeper/authorized_applications", :format=>nil, :id=>nil, :locale=>#<Doorkeeper::Application _id: 53e8f2696c0e32545e000001, created_at: 2014-08-11 16:42:17 UTC, updated_at: 2014-08-11 16:42:17 UTC, name: "Foobar", uid: "d938832444fe519704ec9c6536d8cc40017443f2db66a0bcc1c250bfaf6a4552", secret: "1b1772c69fcd5c55fcb75efbe531992891fdddcd88fe4e158880087d2197671e", redirect_uri: "urn:ietf:wg:oauth:2.0:oob">} missing required keys: [:id]

Am I doing something wrong ?

**Comment by moskeyombus** [comment]
@tute Is the ability to configure which controller the Doorkeeper base controller inherits from something you would still a feature you would be willing to merge?  I have a use case where this would come in handy, would be happy to open a PR

**Comment by tute** [comment]
What is your use case, @moskeyombus? Would reopening `Doorkeeper::ApplicationController` work for you?

**Comment by moskeyombus** [comment]
Basically the application I'm working has a lot of before and after filters in `ApplicationController` that should be utilized by the Doorkeeper controllers.  It's not realistic for me to pull those filters out into helpers (although I realize this is probably best practice).  Ideally, I would be able to configure `Doorkeeper::ApplicationsController` to inherit from my `ApplicationController` instead of `ActionController::Base`.  That would also give me the ability to define my own `BaseController` that `Doorkeeper::ApplicationsController` could inherit from, which may prove useful down the road.

**Comment by tute** [comment]
I am curious about your example: what do those before filters do that need to be run both for user facing, HTML endpoints and for token endpoints?

What I mean by reopening, is adding a `app/controllers/doorkeeper/application_controller.rb` file in your application with following contents:

```ruby
module Doorkeeper
  class ApplicationController < ActionController::Base
    before_filter :do_1
    after_filter :do_2
  end
end
```
This will add behavior at run time to doorkeeper's controller

**Comment by moskeyombus** [comment]
We have various authentication mechanisms defined in our base `ApplicationController` that we use for both our API endpoints and view-rendering HTML endpoints.  I guess technically the method you suggest would work, although it would force me to add `app/controllers/doorkeeper/application_controller.rb` to my project (We've already worked around the default doorkeeper folder structure), as opposed to a adding a single line to the config.

No worries if you'd rather not add that functionality, just thought I would throw the idea out there since you had said a year ago you would be willing to merge a PR.

**Comment by tute** [comment]
If there's a use case that can't be served because of how code is laid out now, I will certainly add the option. Before I want to understand your current issue so I can make sure the issue belongs in doorkeeper and not somewhere else.

To me it sounds like giving the user too much control over how doorkeeper works with that option, and they may as well at that level monkey patch how it works as I was suggesting. Not sure though. Probably we can also add hooks to be run before and after actions.

But the most surprising to me of your case is the authentication that is shared with views and token endpoints. How do you solve this issue, without the configuration option?

**Comment by moskeyombus** [comment]
At the moment I'm solving it by overriding each doorkeeper controller and copy and pasting the necessary code from our `ApplicationController` and `Api::BaseController` (which inherits from `ApplicationController`) into those overridden controllers.  For our API endpoints, we skip various `before_filters` that we include in the `ApplicationController`.  

Ultimately this boils down to a code repetition and organization issue more than anything.  The monkey patch solution will work better than what I'm currently doing, it would look like this for me:

```
module Doorkeeper
  class ApplicationController < ::ApplicationController; end
end
```

To me it seems a little cleaner to provide this as a config option as opposed to explicitly overriding the existing Doorkeeper::ApplicationController, but I may be misunderstanding the reasoning behind that.  I don't think an additional config option gives a user any more control over doorkeeper than monkey patching does, you could effectively override the `Doorkeeper::ApplicationController` with whatever you want right now as it stands.  It really boils down to suggesting users do this via monkey patch vs a config option, I would always lean toward a config option.

**Comment by moskeyombus** [comment]
Ultimately, to answer your original question, reopening `Doorkeeper::ApplicationController` could help to solve my issue, but providing a config option would help to solve my issue without necessitating explicitly redefining and overriding the existing `Doorkeeper::ApplicationController`.

Seeing as this exact pattern is followed in Devise without issue, I don't see why it would be a problem.

**Comment by tute** [comment]
> The monkey patch solution will work better than what I'm currently doing, it would look like this for me:

This wouldn't work though, Ruby would complain about a superclass mismatch. But without changing the superclass, you'd be able to coalesce the overiden controllers into this single one.

> I don't think an additional config option gives a user any more control over doorkeeper than monkey patching does.

Technically it's true. But it does convey an official message to doorkeeper users. A monkey patch is application specific code, and the expectation is that it might or might not break with gem updates. A configuration option is "blessed" by the team maintaining doorkeeper, is meant to be tested and maintained, and used as a non-corner case (that's why it's relevant enough to require it's own option). It also makes the project more complex, adding more states it can be in, rather than following conventions.

I also would always use existing stable APIs than monkey patching as an application developer. But as a library maintainer, before adding any configuration or option I want to make sure it's useful and needed in some cases. Thank you for your time helping me think through this!

> Seeing as this exact pattern is followed in Devise without issue, I don't see why it would be a problem.

This may well be the case, and in that case we'll move forward with the PR.

---

Coming back to your issue, do you think it's surprising `Api::BaseController` inherits from `ApplicationController`, and has to skip some of the global before filters? Shouldn't both `ApplicationController` and `Api::BaseController` inherit from `ActionController::Base`?

What before filters does `Api::BaseController` need?

**Comment by moskeyombus** [comment]
Awesome!  Thanks for talking through that with me, I will get a PR out in the next couple days.  Honestly, having `Api::BaseController` inherit from `ApplicationController` then skipping filters isn't ideal, but there are enough shared methods between the 2 to justify both of them inheriting from _something_.  We haven't really experienced any issues with this other than with Doorkeeper.  

To be fair though, I could still justify adding this config option for us even after we do some reorg and refactoring because we would still likely prefer to have our `Api::BaseController` and whatever the equivalent non-api base controller is both inherit from a shared controller with helpers and methods defined.  Having them both inherit form `ActionController::Base` forces us to write some includes 2x.

Just to give an example, we include an external error reporting library, a logging library, and date helper library that are used application-wide (API and non-API), if our base HTML controller and base API controller inherited `ActionController::Base`, I have to define those includes twice.

**Comment by tute** [comment]
I'll review and merge a PR that adds this option. Thanks!

**Comment by jvenezia** [comment]
Hi, I have a similar usecase here.

It would be nice that `Doorkeeper::ApplicationController` kind of inherit from my own `ApplicationController` since it runs in the same user context for me. I defined various helpers and filters in my `ApplicationController` such as `current_organization`, `set_locale` or error handling and other useful things.

For now I'm just using my own controller instead of using `doorkeeper/authorizations#new`. 

Is this still considered ?
