### ISSUE TITLE
Cleanup AccessGrant and AccessToken?

### ISSUE THREAD

**Issue by waynerobinson** [doorkeeper-gem/doorkeeper#500]
I've had a look through the source code and I can't seem to find any existing method to cleanup the DB tables for AccessGrant and AccessToken for expired and revoked entries. 

Have I missed an existing cleanup method? 

Is there a reason why I wouldn't want to delete expired and revoked entries?

Would you accept a PR for methods to run regularly that delete tokens expired/revoked after a period of time (e.g. daily script that deletes expired/revoked tokens older than 3 months)?

**Comment by bastien-tilkee** [comment]
+1, is there a reason expired tokens are kept in the DB ?

**Comment by tute** [comment]
There's no specific reason that I know of. We could use them to return more meaningful error messages, but AFAIK we don't.

**Comment by francesle** [comment]
Is it safe to remove tokens that have not been revoked? The second part of the query in `expiry_params` could match on an `oauth_access_token` that hasn't been revoked yet, removing a refresh token even though they're not supposed have a TTL expiration. What happens when the client requests with the associated refresh token? Won't the user have to re-authorize the app?

Seems like we should just be cleaning out any tokens that _have_ been revoked, right?

**Comment by warmwind** [comment]
+1. What is the best way to cleanup all the revoked access_tokens? There are too many of them kept in db and not used any longer.

**Comment by TheDeadCode** [comment]
+1

**Comment by tute** [comment]
+1 to what idea, specifically?

Does this [comment](https://github.com/doorkeeper-gem/doorkeeper/issues/500#issuecomment-60865828) address your need?

**Comment by TheDeadCode** [comment]
Yes, as it can be seamlessly integrated into sidekiq for crons. Any feature that let's me clear revoked or expired tokens would be perfectly sufficient.

**Comment by tute** [comment]
Great! For now I'd rather let doorkeeper keep the tokens by default. Can you incorporate that code into your application, and solve your issue? If so, would you be so kind to document this in the wiki? Thank you very much!

**Comment by TheDeadCode** [comment]
I will do a PR into gitlab in the upcoming weeks containing this feature. I'll document it right after, if I ever find the time. Cheers!

**Comment by GUI** [comment]
If it helps anyone else, here's a slight variation on @waynerobinson's approach, with the following differences:

- Uses PostgreSQL compatible SQL query for the `created_at` and `expires_in` math.
- Getting to @francesle's earlier point, it does not remove tokens unless they're explicitly revoked or expired (tokens that aren't expired or revoked will remain around indefinitely).
- Rake task instead of a class.

```ruby
desc "Trim old OAuth tokens from the tables (default: > 30 days)."
task :trim_doorkeeper_tokens => :environment do
  delete_before = (ENV["DOORKEEPER_DAYS_TRIM_THRESHOLD"] || 30).to_i.days.ago
  expire = [
    "(revoked_at IS NOT NULL AND revoked_at < :delete_before) OR " +
    "(expires_in IS NOT NULL AND (created_at + expires_in * INTERVAL '1 second') < :delete_before)",
    { :delete_before => delete_before },
  ]
  Doorkeeper::AccessGrant.where(expire).delete_all
  Doorkeeper::AccessToken.where(expire).delete_all
end
```

**Comment by hubertjakubiak** [comment]
If you are going to delete old access tokens for the first time after long period of time not doing it at all, it could be safer to remove them in batches like:

```
Doorkeeper::AccessGrant.where(expire).in_batches(&:delete_all)
Doorkeeper::AccessToken.where(expire).in_batches(&:delete_all)
```
