### ISSUE TITLE
application scopes saved as '' instead of NULL

### ISSUE THREAD

**Issue by kenn** [doorkeeper-gem/doorkeeper#539]
#469 added a NOT NULL column with an empty string as a default value.

```ruby
add_column :oauth_applications, :scopes, :string, null: false, default: ''
```

However, this is not compatible with:

- Oracle, as [it treats '' as NULL](http://stackoverflow.com/questions/203493/why-does-oracle-9i-treat-an-empty-string-as-null)
- [clear_empty_attributes](https://github.com/collectiveidea/clear_empty_attributes) or [nilify_blanks](https://github.com/rubiety/nilify_blanks) as what they do is never allow '' in the system by applying:

```ruby
class ActiveRecord::Base
  before_validation :nullify
  before_save :nullify

  def nullify
    @attributes.each do |key, value|
      self[key] = nil if value.is_a?(String) && value.blank?
    end
  end
end
```

at `ActiveRecord::Base` level. Therefore, it raises an exception when gets saved.

I don't want to start debating this decades-old topic (NULL or '') but want to remove the NOT NULL constraint, and use NULL instead of ''.

Would it be accepted if I create a PR for that?

**Comment by garyharan** [comment]
I'm also having this issue :-(

**Comment by tute** [comment]
Input from @sgrif in this issue is very much appreciated.

**Comment by sgrif** [comment]
I agree with @tutec. It should not be Doorkeeper's problem if other gems decide to change the meaning of an empty string (which strikes me as a really bad idea).

If you need to use those gems, or an oracle back end, you can pretty easily change the schema for your app. I don't think having doorkeeper bend over backwards for an edge case makes sense though.

**Comment by garyharan** [comment]
I'm not using the gems mentioned above.  I'm getting the issue with the standard oracle_enhanced gem and doorkeeper when I try to create an OAuth application.

**Comment by tute** [comment]
Thank you @sgrif. @garyharan would a PR like this solve your current issue?

**Comment by kenn** [comment]
> If you need to use those gems, or an oracle back end, you can pretty easily change the schema for your app. I don't think having doorkeeper bend over backwards for an edge case makes sense though.

@sgrif I'm afraid you're missing the point. As the doorkeeper's internal logic depends on the fact that the field *always* has a string, it's not possible to just edit the migration - we need to change both migration **and** code to support Oracle.

> (which strikes me as a really bad idea)

I'll try to explain why it is not. Here's three ways to handle a "logical" empty value for a string field.

1. Store empty string as ''
1. Store empty string as NULL
1. Store empty string as '' OR NULL randomly

Doorkeeper does 1, Oracle and I do 2. Typical Rails apps do 3.

3 is the worst yet it is pretty common with Rails. Say, you have a `t.string :text` field, and assign from `params[:text]`. You can get either `NULL` or `''` depending on how you save the model.

I believe we can agree that two random representations for the same logical value (or non-value, if pedantic) is bad. Both 1 and 2 share a clear goal - to avoid three-valued logic like 3.

The Rails' way of handling it is to use `blank?` instead of `nil?` or `empty?`, but as it is a Ruby-land logic, it cannot be easily translated into SQL queries.

For instance, if you want to find records with a present string value, you need `where.not(text: nil).where.not(text: '')` which is required to support typical Rails apps. Both 1 and 2 solves that problem - it's either `where.not(text: nil)` or `where.not(text: '')`.

Downside of 1 is it cannot support Oracle.

Downside of 2 is that it gets complicated when we need to query something like `LENGTH(text) < 20`. It would be easier if empty values are stored as `''` instead of NULL.

So there are trade-offs - I don't see why 2 is a "really bad idea" compared with 3.

To me, 2 is the logical choice as the greatest common denominator for all databases - there's a reason why you don't see `null: false, default: ''` in the real world.

**Comment by crabonature** [comment]
First question is this from logical point are proper thing: `null: false, default: ''`?
What that means? We do not allow `NULL` (which represents for example no information in database), but on the other side allow and by default put there `''` (what represents `''`? no information or something else from DB perspective? ) When and why we could potentially store `''` in relational database instead of NULL to represent no information?

Indeed oracle_enhanced gem translate Strings into VARCHAR2 type https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L452. And Oracle treats `''` for VARCHAR2 type as NULL value. From Oracle Database something like that `null: false, default: ''` is a bad idea and will not work.

**Comment by tute** [comment]
@kenn thanks for your answer, I follow what you say.

> Downside of 1 is it cannot support Oracle.

That's indeed a big one.

> Downside of 2 is that it gets complicated when we need to query something like LENGTH(text) < 20. It would be easier if empty values are stored as '' instead of NULL.

Another downside is we need more logic. The only way to guarantee the option you suggest is converting empty strings to `nil` wherever the database calls happen. If we assume that those changes happen only through doorkeeper's admin interface we could take care of that adding code and tests, it's a finite set of options (although we have to find them). But why doing it in code if the database can already ensure the data type? As a programmer I find it less surprising: the value always has the same interface because it's always the same type.

This also answers your question, @crabonature. A longer argument on why should `NULL` be used as sparingly as possible: http://www.bennadel.com/blog/85-why-null-values-should-not-be-used-in-a-database-unless-required.htm.

> To me, 2 is the logical choice as the greatest common denominator for all databases - there's a reason why you don't see null: false, default: '' in the real world.

In my opinion the reason is that it's easier (but not simpler). That's the reason why [Tony Hoare allowed null references in his object oriented language](http://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare).

---

I'm surprised about Oracle's implementation, and I would like a solution for all DBs that minimizes `nil`s in Ruby land.

**Comment by kenn** [comment]
@tute thanks for your comment.

> Another downside is we need more logic. The only way to guarantee the option you suggest is converting empty strings to `nil` wherever the database calls happen.

Yes, and the 10 lines of code that I attached in OP does that for you automatically - it's proven to work as I've never had any problems with it in my Rails projects since 2006, from small to (very, very) large scale. I always wanted it to be a part of ActiveRecord's proper, in fact.

But in reality, most Rails devs don't care. Most don't bother to exactly write `where('text IS NULL OR text = ""')`. I guess they just do either `where(text: nil)` or `where(text: '')` and don't even notice some records might be missing.

> ... This also answers your question, @crabonature. A longer argument on why should NULL be used as sparingly as possible: http://www.bennadel.com/blog/85-why-null-values-should-not-be-used-in-a-database-unless-required.htm.

As I demonstrated with the `LENGTH(text) < 20` example, I'm aware of this issue, but I disagree with the conclusion of this article.

It does fix **some** problems, but it also creates new problems like, losing the power of `NOT NULL` constraints, as there's no string equivalent like `NOT EMPTY STRING`.

What's more, we're only talking about strings here, but how about numbers? Normalize to 0? How about date? 1970-01-01?

Those types have the same set of problems like `ABS(num) < 20`. Do we really want to populate `0` for nil, to represent a missing value? If the answer is no, the design lacks consistency. Consistency between types is another reason that I'd prefer normalizing to `NULL` rather than `''`.

At least - like it or not - Ruby's nil is consistent.

```ruby
> nil.to_s
 => ""
> nil.to_i
 => 0
> nil.to_a
 => []
> nil.to_h
 => {}
```

(also as a side note, in 2006, [Matz seriously considered](http://www.rubyist.net/~matz/20060902.html) to change `nil.to_s` to return `nil` instead of `""`.)

The crux of the issue is the impedance mismatch between SQL and Ruby.

In a nutshell, SQL is a declarative, functional language that is optimized for large "set" operations. Which means that an exception in the middle of execution (e.g. error at the 999,999th record in a million rows) is prohibitively expensive, thus not acceptable.

Therefore, NULL is designed to return NULL on any operations to tolerate more irregularities. NULL emerged as a necessary evil on the [open-world assumption](http://en.wikipedia.org/wiki/Open-world_assumption).

```sql
SELECT LENGTH(NULL) < 20
=> NULL
```

Which in essence can be translated to the following Ruby code:

```ruby
class NilClass
  def method_missing(*args)
    nil
  end
end

nil.size < 20
=> nil
```

Just like obj-c returns nil for any methods on nil.

And this impedance mismatch is so intrinsic that cannot be resolved without introducing destructive changes (like above) on Ruby. ([Squeel](https://github.com/activerecord-hackery/squeel) fills some of the gaps, though)

More modern approaches like maybe-monad in Haskell or optional-chaining in Swift are emerging too. The same idea has been discussed with Ruby in many ways: https://robots.thoughtbot.com/if-you-gaze-into-nil-nil-gazes-also-into-you (Actually, I often use value objects like the `Some` / `None` class in this example a lot.)

I have a mixed feeling about Oracle's implementation, but the fact that Oracle does not handle empty strings tells that one thing is crystal clear... the world can be modeled without `''`.

But then again, let me be clear that I'm not saying Doorkeeper should embrace my idea. I just wanted to share that not everyone agrees that `NULL` should be avoided whenever possible, and some people prefer `NULL` over `''` for valid reasons.

Anyway... should I create a PR?

**Comment by tute** [comment]
Thanks for your thoughtful comment @kenn.

---

> > Another downside is we need more logic. The only way to guarantee the option you suggest is converting empty strings to nil wherever the database calls happen.
> Yes, and the 10 lines of code that I attached in OP does that for you automatically - it's proven to work as I've never had any problems with it in my Rails projects since 2006, from small to (very, very) large scale. I always wanted it to be a part of ActiveRecord's proper, in fact.

We'd need 10x2 lines, for saving `nil`s and recovering `""` with the potentially slow `after_initialize` ActiveRecord hook. See the end of this comment. The alternative I fear and reject is logic to talk to strings that might be `nil`s spread out everywhere we need.

---

> But then again, let me be clear that I'm not saying Doorkeeper should embrace my idea. I just wanted to share that not everyone agrees that NULL should be avoided whenever possible, and some people prefer NULL over '' for valid reasons.

I agree we can successfully model software with or without `NULL`s and `nil`s, and allowing them or not is a design choice each with pros and cons.

As stated, I'll minimize the use of those constructs as much as I can in the software I maintain. I'll also try to make my contributions useful to the widest possible audience. Useful implies I'll take decisions I wouldn't if I were the only user of the software. Useful also implies  reliable, but many ORMs I don't use and can't guarantee their reliability. That's the reason I've been pushing different ORMs further away from doorkeeper (and merit gem), and in my ideal world I'd extract them as their own gems/plugins.

I have been that Rails programmer who doesn't even know if there are all rows after a `SELECT`, because there may be empty strings or nulls or some other magic value that means the same, and I can continue to be and do it "right". I prefer to have a simpler design that guarantees that I will never have that problem (or even question) again. The database spitting `nil`s into my program imply more conditionals, more just-in-case initializations, and more room for bugs.

Possible outcomes (italics for _very_ subjective terms):

1. ActiveRecord handled this. doorkeeper (and any other gem and app) has the potential to stay simple while supporting this case, and we keep this issue open until then. @sgrif do you see this happening in any _near_ future?

2. Rails won't fix it, but there's _a ton_ of people needing this, and I accept a PR @kenn proposes, however it solves it.

3. Rails won't fix it, but the solution is _simple enough_. This might be: we add an `oracle` adapter in https://github.com/doorkeeper-gem/doorkeeper/tree/e8d6c36/lib/doorkeeper/orm that has a `before_save`, an `after_initialize`. We also add it's migrations without `null: false`. The adapter will allow `NULL`s in the database but not in "doorkeeper core". The `after_initialize` penalty (if any) only affects Oracle.

**Comment by tute** [comment]
In my ideal world, ActiveRecord does the conversion. In the real world (if many people need it) I maintain it. In a possible world, we find a solution that doesn't imply design changes to doorkeeper.

**Comment by tute** [comment]
It seems Rails 5 is walking this way: https://github.com/rails/rails/blob/8c752c7ac739d5a86d4136ab1e9d0142c4041e58/activerecord/lib/active_record/attributes.rb#L13

Will study later!

**Comment by tute** [comment]
Closing for now, if it's still an issue we'll reopen and address. Thanks for your time discussing this, Kenn.

**Comment by kenn** [comment]
Yeah, understood. I decided to tweak my code so that we can handle it as an exceptional case.

```ruby
class ActiveRecord::Base
  before_validation :nilify_empty_strings
  before_save :nilify_empty_strings # needed to work correctly with update_attribute too

protected

  def nilify_empty_strings
    attributes.each do |key,value|
      if value.is_a?(String) && value.blank? && !is_a?(Doorkeeper::Application)
        self[key] = nil
      end
    end
  end
end
```

Doorkeeper is a great gem for what it does - thanks for your time discussing the topic! 👍
