### ISSUE TITLE
There is a problem in the  doorkeeper/lib/doorkeeper/oauth/authorization_code_request.rb.

### ISSUE THREAD

**Issue by blackspace** [doorkeeper-gem/doorkeeper#752]
I traced the doorkeeper gem by the  codes:

```
def validate_redirect_uri
    grant.redirect_uri == redirect_uri 
    ::Rails.logger.info  grant.redirect_uri
    ::Rails.logger.info redirect_uri  
end
```

This is my logger file:

<pre>
I, [2015-11-22T22:52:20.493163 #23447]  INFO -- : http://gnuhacker.qphelper.com/users/auth/my_user/callback
I, [2015-11-22T22:52:20.493260 #23447]  INFO -- : http://gnuhacker.qphelper.com/users/auth/my_user/callback?code=fd14616ecc01117414cc70c6da644c1cae8cd8655cd826e955ef37076d091ede&state=f512cb3386e7b7ce3e84865bb42e08cca024fc4b4fd6ac48
</pre>

Why isn't equal between the  redirect_uri  ?

**Comment by tute** [comment]
I have no idea! :)

The issue you describe seems very specific to your applications and their configuration. I suggest that you ask about it in http://stackoverflow.com/questions/tagged/doorkeeper, which will get attention
from more people than in this issue tracker. Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

For now, I will close this issue, and if you continue having problems and can add more context we can reopen. Thanks!
