### ISSUE TITLE
Application id and resource_owner id not matched while creating a grant or access_token

### ISSUE THREAD

**Issue by Anoop1989** [doorkeeper-gem/doorkeeper#755]
Hi,

There is a condition check while revoking a token in tokens_controller as below

`if token && doorkeeper_token.same_credential?(token)`

Why is `doorkeeper_token.same_credential?(token)` not being called while authorizing a grant or creating  a access_token?

Awaiting your concerns.

**Comment by tute** [comment]
When revoking, you have to verify that you have a valid access token to revoke. You authenticate with a token and a token string to revoke, and doorkeeper verifies they belong to the same user.

When issuing new tokens authorization happens without the need of comparison with another token.

Thanks for your question.

**Comment by Anoop1989** [comment]
But this creates wrong mapping of resource_owner and application(oauth client) with authorization_grant, if two different client are trying to authorize in the same browser.

This is because the ResourceOwner being set in the dooorkeeper initializer file and resource_owner is set using the session attribute.

**Comment by maciekkolodziej** [comment]
@Anoop1989 I'm not sure if I understand your issue correctly, but I've checked how doorkeeper works with two separate apps in one browser and I think it works well if you have your apps sessions set up correctly.

When you're running two apps locally, for example [this one](https://github.com/doorkeeper-gem/doorkeeper-sinatra-client) with default setup, it won't work because those two apps sessions will interfere, and session is the place where those apps store access_tokens.  To make it work, you need to either use different domains (app1.loc:9191, app2.loc:9292) or set different session cookie keys like:

`use Rack::Session::Cookie, :key => 'rack.session.app1',
      :path => '/',
      :secret => 'your_secret'`

instead of `enable :sessions` in `doorkeeper_client.rb` file.

In production, you need to set session cookie keys only if two apps will be placed on the same domain.

Please let me know if that helped or I've misunderstood the issue.

**Comment by nbulaj** [comment]
Thank you @maciekkolodziej. I will close this issue due to stale status and blank activity of the @Anoop1989. If somebody will face the same problem and the solution above wouldn't work for him - everyone can open a new issue.
