### ISSUE TITLE
websocket-rails integration

### ISSUE THREAD

**Issue by talski** [doorkeeper-gem/doorkeeper#850]
Hello, I'm using websocket-rails and I'd like to use some sort of token authorisation with, don't know if doorkeeper would be the best choice, but if it can, how could I use doorkeeper_authorize! in my controllers using WebsocketRails::BaseController? There's a way to manually test if a certain token is valid?

**Comment by tute** [comment]
OAuth is designed to work in a stateless network, whereas websockets are stateful by design. Once you authenticate once, you can open a channel, and you don't need any tokens afterwards.

I'm not sure exactly how you would authenticate for your specific application, it will depend on your tech and needs. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/doorkeeper, which will get attention from more people than in this issue tracker.

Thanks!
