### ISSUE TITLE
Token revocation uses wrong authorization method

### ISSUE THREAD

**Issue by jclem** [doorkeeper-gem/doorkeeper#875]
The [OAuth 2.0 Token Revocation spec](https://tools.ietf.org/html/rfc7009#section-2.1) states that when revoking a token, "the client also includes its authentication credentials as described in [Section 2.3. of \[RFC6749\]](https://tools.ietf.org/html/rfc6749#section-2.3)".

The spec's example request for revocation looks like this:

```
POST /revoke HTTP/1.1
     Host: server.example.com
     Content-Type: application/x-www-form-urlencoded
     Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

     token=45ghiukldjahdnhzdauz&token_type_hint=refresh_token
```

Note the HTTP Basic authentication, not Bearer. The spec goes on to say that the authorization server "first validates the client credentials (in case of a confidential client) and then verifies whether the token was issued to the client making the revocation request.  If this validation fails, the request is refused and the client is informed of the error by the authorization server as described below".

It appears as though Doorkeeper instead [authorizes the request using HTTP Bearer with an access token](https://github.com/doorkeeper-gem/doorkeeper/blob/c13ab298489945964db4f45ab3c37885223d28b8/spec/requests/flows/revoke_token_spec.rb#L17), even though [a code comment seems to imply otherwise](https://github.com/doorkeeper-gem/doorkeeper/blob/c13ab298489945964db4f45ab3c37885223d28b8/app/controllers/doorkeeper/tokens_controller.rb#L14).

**Comment by tute** [comment]
Thank you for reporting. This has been reported by @f3ndot too, and we are now working on it. Thanks!

**Comment by jclem** [comment]
You're welcome, and thank you for maintaining Doorkeeper!

**Comment by f3ndot** [comment]
This issue has been assigned CVE-2016-6582 as properly authenticated clients will not have their token revoked with no error from Doorkeeper to indicate otherwise.

@tute and myself have been coordinating a fix as this also affects public, non-confidential clients as well.

**Comment by f3ndot** [comment]
The security implication is that clients who "log out" a user expect to have the corresponding access & refresh tokens revoked, preventing an attacker who may have already hijacked the session from continuing to impersonate the victim. Because of this bug, this is not the case. As far as MITRE and OWASP are concerned this counts as [broken authentication design](https://www.owasp.org/index.php/Top_10_2013-A2-Broken_Authentication_and_Session_Management).

Unless I'm mistaken, all clients (public or confidential) that send well-formed, [RFC 7009](https://tools.ietf.org/html/rfc7009) compliant requests are affected by this bug. All versions of Doorkeeper that have supported this feature ([1.2.0](https://github.com/doorkeeper-gem/doorkeeper/blob/master/NEWS.md#120---2014-05-02) and later) is affected by this bug.

**Comment by tute** [comment]
Thank you both!

**Comment by f3ndot** [comment]
Added an advisory entry to https://github.com/rubysec/ruby-advisory-db/pull/268

**Comment by f3ndot** [comment]
Findings published: http://seclists.org/oss-sec/2016/q3/332
