### ISSUE TITLE
Multiple access token generation from one refresh token.

### ISSUE THREAD

**Issue by sagar18041** [doorkeeper-gem/doorkeeper#884]
I am able to generate multiple access token from single refresh token unless the refresh token is revoked.
W.R.T [Revoke Refresh Token on access token use](https://github.com/doorkeeper-gem/doorkeeper/pull/769).
We can generate multiple access token from previous refresh token unless the newly generated access_token is used, once we use the newly generated access token the previous refresh token is revoked.
So my issue is if someone hits the refresh token generation multiple times with a valid refresh token it will generate n number of access token, which will populate the access token table.

**Comment by tute** [comment]
Is this a bug? If so, what would be the desired outcome? If addressed, would it be backwards compatible?

**Comment by sagar18041** [comment]
Its a silent bug, as till date we were not facing this issue as the condition never came in to picture. But suddenly one of our api client started to hit the /oauth/token request multiple times per seconds to generate new access_token from refresh token that when this issue came up.

W.R.T [Revoke Refresh Token on access token use](https://github.com/doorkeeper-gem/doorkeeper/pull/769)
Desired outcome is:

1. Whenever access_token generation request is made from refresh token, we search if already a access_token is generated for similar request.
    
    - If YES, then check if the access_token is valid or not (expiry)
    - If NO, generate one.

and finally return the new/existing token.

I have already forked your repository and did the changes accordingly. I was wondering that am I the  only one who is facing the issue, or is this issue already addressed.

The solution is for version 4.0.0 +

**Comment by brianoqr** [comment]
I can confirm that in doorkeeper (4.2.0)  - refresh tokens are indefinitely valid. Every refresh_token ever made, is forever valid. This can not be anything other than a major security issue, or I am missing some sort of configuration. 

If i manually set the revoked_at date then the refresh token also becomes invalid and that works. 

But by default after refresh the revoked_at date is not set so I can revalidate with a refresh_token grant and then get a new authorization token and a new refresh_token forever with all refresh tokens that get generated.

**Comment by sagar18041** [comment]
@brianoqr Your points are totally valid, but my concern is with the new access_token generated with the refresh token.
So in the current scenario we are able to generate infinite set of access_token and refresh_token,
instead what we are trying to achieve is, we should get same set of access_token and refresh_token unless access_token is expired or refresh_token is revoked.
In order to prevent multiple generation of access_token and refresh_token sets from one refresh_token.

p.s. : if you need i can provide with a scenario of the same.

**Comment by brianoqr** [comment]
Yes i understand, your solution of returning the same access token/refresh token if the refresh token being used has not been revoke and already used, that is acceptable to me. The access token are not as big of a concern as the refresh token, since refresh tokens never expire. 

Perhaps the caveat that created this situation is in the scenario you are suggesting (which i totally agree with) for example:
- a client for some reason never received the new refresh_token, after a refresh call
- time passes and the client uses the "old" refresh token
- at this point the client can potentially receive an already expired access_token

This is not necessarily a problem, but could be awkward for certain clients. As then the newly delivered refresh_token can be used, but most clients expect a newly sent access_token to be valid, so this can be solved by reseting the TTL as well. 

I would prefer to get an expired access_token in this scenario as opposed to having a database full of living refresh_tokens

**Comment by sagar18041** [comment]
So, i would suggest 
we should only **resend** the valid set of access_token and refresh_token, to prevent already expired access_token.
if the set is expired only then we should generate a new set, else we should continue to resent the same set.

**Comment by pguelpa** [comment]
This seems to be related to #886. Also it seems like there is logic that is [trying to revoke the refresh token](https://github.com/doorkeeper-gem/doorkeeper/blob/2cbd70f31fec5f22f01a162b5e38745f44003d54/lib/doorkeeper/oauth/refresh_token_request.rb#L39) and even [a spec for it](https://github.com/doorkeeper-gem/doorkeeper/blob/2cbd70f31fec5f22f01a162b5e38745f44003d54/spec/lib/oauth/refresh_token_request_spec.rb#L38) after it's been used, but it's not working for some reason.

**Comment by pguelpa** [comment]
Update to this, looks like this was a feature added in #769. In order to expire the previous refresh token you need to use the new access token, otherwise the refresh token will continue to be valid. If you want to make it so that the refresh token is revoked immediately I believe you can do so by removing the `oauth_access_tokens.previous_refresh_token` column.

**Comment by nbulaj** [comment]
I take a look at the OAuth2 docs.. And don't sure if that a problem (see my comment in another issue https://github.com/doorkeeper-gem/doorkeeper/issues/886#issuecomment-258456222 )

**Comment by chulkilee** [comment]
Shouldn't this be closed?

**Comment by tute** [comment]
> Looks like this was a feature added in #769. In order to expire the previous refresh token you need to use the new access token, otherwise the refresh token will continue to be valid. If you want to make it so that the refresh token is revoked immediately I believe you can do so by removing the oauth_access_tokens.previous_refresh_token column.

This is correct. Closing this issue. Thanks!
