### ISSUE TITLE
personal access tokens ?

### ISSUE THREAD

**Issue by grosser** [doorkeeper-gem/doorkeeper#902]
We got OAuth running, but we'd also like to make a user able to generate "personal" tokens for their commandline usage or 1-off apps ... is that supported or should we add a custom UI ?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/doorkeeper, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!
