### ISSUE TITLE
any helpful documents for migrate from v1.4.1 to v4.2.5?

### ISSUE THREAD

**Issue by redtear1115** [doorkeeper-gem/doorkeeper#966]
hi pros,
I am trying to upgrade our system from v1.4.1 to v4.2.5
the only document I found is [here](https://github.com/doorkeeper-gem/doorkeeper/wiki/Migration-from-old-versions). It still have long way to go...

My major problems as below. 
**application_id** on **oauth_access_grants** and **oauth_access_tokens**, are both changed to use reference of application and add foreign_key as application_id. How can I migrate old schema to new? I have to keep all data.
Thanks

**Comment by maclover7** [comment]
Hi @redtear1115! Best bet is to follow the NEWS.md file through all of the changes. Since you are migrating across almost three major version of Doorkeeper, you may have to run some manual database queries / do some awkward things to migrate. I recommend trying to Google around for different upgrading blog posts between major versions of Doorkeeper as a baseline. Best of luck with the upgrade!
